name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      S3_BUCKET: my-terraform-state-backend-unique-name-123
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for Deployment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker Image
        run: docker build -t my-website-image . 

      - name: Run Container and Verify Port
        run: |
          docker run -d -p 8080:80 --name test-container my-website-image
          # Wait a moment for Nginx to start
          sleep 5 
          # Check if the website endpoint returns HTTP 200 (Success)
          curl -sI http://localhost:8080 | grep "HTTP/1.1 200 OK"

      - name: Deploy static site to S3 (CD Step)
        run: |
          aws s3 sync ./ s3://${{ env.S3_BUCKET }} --delete
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "terraform/*" \
            --exclude "test.sh" \
            --exclude "Dockerfile"